### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by flymzero** [The-conchs/ROCK_5B_Project#1]
老哥我看你文字描述是1.41，我看图片壳上显示1.42，版本是哪个哈😄

**Comment by The-conchs** [comment]
emmmm。。。。。这个版本指的是rock5B的版本，模型文件还是1.41的那个（可能外观写的还是1.42）不过问题不大，都能用的1.41和1.42
Rock5B都能用（抱歉哈~这个项目只是我一时兴起推上去的，最近又因为工作忙就一直没有维护

flyzero ***@***.***> 于 2023年3月10日周五 上午9:08写道：
